version: "1"

services:
  - name: devjobs-api
    type: web
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: "mongodb+srv://juanmoriones012:juanmoriones1212@juan.trebmh5.mongodb.net/?retryWrites=true&w=majority&appName=juan"
      - key: SECRET
        value: mipalabra5689
      - key: KEY
        value: abcdefghi